import { BaseError } from '../index'
import { HighLevelError, LowLevelErrorInternal } from '../interfaces'

/**
 * Improved error class generated by the ErrorRegistry.
 **/
export class BaseRegistryError extends BaseError {
  constructor (
    highLevelErrorDef: HighLevelError,
    lowLevelErrorDef: LowLevelErrorInternal
  ) {
    super(lowLevelErrorDef.message)

    this.withErrorCode(highLevelErrorDef.code)

    if (highLevelErrorDef.statusCode) {
      this.withStatusCode(highLevelErrorDef.statusCode)
    }

    if (highLevelErrorDef.logLevel) {
      this.withLogLevel(highLevelErrorDef.logLevel)
    }

    if (lowLevelErrorDef.statusCode) {
      this.withStatusCode(lowLevelErrorDef.statusCode)
    }

    if (lowLevelErrorDef.type) {
      this.withErrorType(lowLevelErrorDef.type)
    }

    if (lowLevelErrorDef.subCode) {
      this.withErrorSubCode(lowLevelErrorDef.subCode)
    }

    if (lowLevelErrorDef.logLevel) {
      this.withLogLevel(lowLevelErrorDef.logLevel)
    }
  }
}
