import { BaseError } from '../index'
import { HighLevelErrorDef, LowLevelErrorInternal } from '../interfaces'

/**
 * Improved error class generated by the ErrorRegistry.
 **/
export class BaseRegistryError extends BaseError {
  constructor (
    highLevelErrorDef: HighLevelErrorDef,
    lowLevelErrorDef: LowLevelErrorInternal
  ) {
    super(lowLevelErrorDef.message)

    if (highLevelErrorDef.statusCode) {
      this.withStatusCode(highLevelErrorDef.statusCode)
    }

    if (lowLevelErrorDef.statusCode) {
      this.withStatusCode(lowLevelErrorDef.statusCode)
    }

    if (lowLevelErrorDef.code) {
      this.withErrorCode(lowLevelErrorDef.code)
    }
  }
}
